### ISSUE TITLE
Division by Zero

### ISSUE THREAD

**Issue by olafgeibig** [Furrmidable-Crew/ccat_summarization#1]
**Describe the bug**
```
cheshire_cat_core-security  |   warnings.warn(
cheshire_cat_core-security  | [2024-01-09 13:04:39.463] ERROR  cat.mad_hatter.mad_hatter.MadHatter.execute_hook::263 => 'Error in plugin ccat_summarization::before_rabbithole_stores_documents'
cheshire_cat_core-security  | [2024-01-09 13:04:39.506] ERROR  cat.mad_hatter.mad_hatter.MadHatter.execute_hook::264 => ZeroDivisionError('integer division or modulo by zero')
cheshire_cat_core-security  | [2024-01-09 13:04:39.511] WARNING cat.mad_hatter.mad_hatter.MadHatter.execute_hook::266 => ('To resolve any problem related to Summarization plugin, contact the creator '
cheshire_cat_core-security  | [2024-01-09 13:04:39.511] WARNING cat.mad_hatter.mad_hatter.MadHatter.execute_hook::266 => 'using github issue at the link '
cheshire_cat_core-security  | [2024-01-09 13:04:39.511] WARNING cat.mad_hatter.mad_hatter.MadHatter.execute_hook::266 => 'https://github.com/Furrmidable-Crew/ccat_summarization')
cheshire_cat_core-security  | Traceback (most recent call last):
cheshire_cat_core-security  |   File "/app/cat/mad_hatter/mad_hatter.py", line 254, in execute_hook
cheshire_cat_core-security  |     tea_spoon = hook.function(
cheshire_cat_core-security  |   File "/app/cat/plugins/ccat_summarization/summarization.py", line 35, in before_rabbithole_stores_documents
cheshire_cat_core-security  |     progress = (n * 100) // n_summaries
cheshire_cat_core-security  | ZeroDivisionError: integer division or modulo by zero
```
**To Reproduce**
Upload documents into an empty cat

**Expected behavior**
No errors

**Additional context**

**Comment by nicola-corbellini** [comment]
Did you have any other plugin operating on the ingested files?

**Comment by olafgeibig** [comment]
![Screenshot 2023-10-18 at 13 35 09](https://github.com/Furrmidable-Crew/ccat_summarization/assets/295644/6ee6d7f5-9935-48bb-8474-5ec23f042dbf)

**Comment by olafgeibig** [comment]
![Screenshot 2024-01-10 at 10 36 27](https://github.com/Furrmidable-Crew/ccat_summarization/assets/295644/ef1db60d-afa4-404e-8e7a-fe1ec5da640f)

**Comment by nicola-corbellini** [comment]
Mmh, ok that's strange.
I'll handle this, but `n_summaries` is never supposed to be zero unless the length of ingested docs is zero (`len(docs)`)
